version: "3"
services:
  app:
    build: .
    command: pm2-dev ./app/server.js
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - .:/home/nodejs/app
      - ./node_modules:/home/nodejs/node_modules

  nginx:
    image: nginx:1.19
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - "27017:27017"
